disabled_rules:
  - notification_center_detachment
  - redundant_objc_attribute
  - unused_closure_parameter
  - weak_delegate
  - empty_parentheses_with_trailing_closure
  - legacy_constructor
  - type_name
  - nesting
  - file_length
  - line_length
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - block_based_kvo
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - fatal_error_message
  - file_name_no_space
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - inert_defer
  - last_where
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - private_over_fileprivate
  - redundant_nil_coalescing
  - single_test_class
  - trailing_closure
  - todo
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - redundant_type_annotation
type_body_length:
  warning: 300
  error: 400
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 90
    error: 120
reporter: "xcode"
